import random
import time


def is_prime(num: int) -> bool:
    """return True if the given number is a prime number
    or False if it's not

    Args:
        num (int): number to test

    Returns:
        bool: True if prime, False if not
    """
    for i in range(2, num):
        if (num % i == 0):
            return (False)
    return (True)


def fibonacci_generator():
    """A generator that will generate the fibonaci sequence

    Yields:
        int: the ncall number on the fibonaci sequence
    """
    a = 0
    b = 1
    while True:
        yield a
        a, b = b, a + b


def prime_number_gen():
    """A generator that will return prime number

    Yields:
        int: the ncall prime number
    """
    a = 2
    while True:
        if (is_prime(a) is True):
            yield a
        a += 1


def fibonacci(num: int) -> None:
    """A function that will display the
    'num' number of the fibonacci sequence

    Args:
        num (int): n number of the sequence
    """
    string = ""
    gen = fibonacci_generator()
    for k in range(10):
        string += f" {next(gen)},"
    print(f"Fibonacci sequence (first {num}):{string}")


def prime_number(num: int):
    """A function that will display the
    'num' first prime number

    Args:
        num (int): n first prime number
    """
    string = ""
    gen = prime_number_gen()
    for k in range(num):
        string += f" {next(gen)},"
    print(f"Prime numbers (first {num}):{string}")


Alice = {"name": "alice", "level": 5, "xp": 0}
Bob = {"name": "bob", "level": 12, "xp": 0}
Charlie = {"name": "charlie", "level": 8, "xp": 0}


Players = [Alice, Bob, Charlie]


Events = [
    {"id": 1, "event_name": "killed monster", "xp_value": 20},
    {"id": 2, "event_name": "killed big monster", "xp_value": 30},
    {"id": 3, "event_name": "killed boss", "xp_value": 150},
    {"id": 4, "event_name": "found treasure", "xp_value": 15},
    {"id": 4, "event_name": "found rare treasure", "xp_value": 50},
    {"id": 5, "event_name": "meet the creator", "xp_value": 500},
    {"id": 6, "event_name": "finished a quest", "xp_value": 60},
    {"id": 7, "event_name": "finished the game, you can't do that ?",
     "xp_value": 1000},
    {"id": 8, "event_name": "cooked", "xp_value": 5},
    {"id": 9, "event_name": "transaction realised", "xp_value": 10},
    {"id": 10, "event_name": "transaction realised", "xp_value": 10}
]


def return_best_player(Players: list) -> dict:
    """A simple function that will iterat throught the Players list
    and return the player with biggest level

    Args:
        Players (list): All Players on the server

    Returns:
        dict: the best player
    """
    best_player = None
    for player in Players:
        if (best_player is None or player["level"] > best_player["level"]):
            best_player = player
    return (best_player)


def stream_analytics(Players: list, total_event_count: int,
                     treasur_event: int, level_up_event: int) -> None:
    """A function to display some events state

    Args:
        Players (list): All players on the server
        total_event_count (int): total events
        treasur_event (int): total treasur events
        level_up_event (int): total level up events
    """
    print("\n=== Stream Analytics ===")
    print(f"Total events processed: {total_event_count}")
    print(f"Hight-level players (10+) {return_best_player(Players)['level']}")
    print(f"Treasure events: {treasur_event}")
    print(f"Level-up events: {level_up_event}")


def generate_events(Players: list, event_number: int):
    """A generator that will generate random event by picking randomly
    a name on the players list and an event on the event list
    The generator will also attribut the right quantity of xp
    (given by the event selected) to the player selected
    if a player level up, the leveled up event will be send too

    Args:
        Players (list): All players on the server
        event_number (int): how many event we want

    Yields:
        tuple: the player and the event selected
    """
    k = 0
    while k < event_number:
        player, event = (Players[random.randint(0, len(Players) - 1)],
                         Events[random.randint(0, len(Events) - 1)])
        yield player, event
        player["xp"] += event["xp_value"]
        if (player["xp"] >= 500):
            while (player["xp"] >= 500):
                player["level"] += 1
                player["xp"] = player["xp"] - 500
            k += 1
            event = {"id": 11, "event_name": "leveled up", "xp_value": 0}
            yield player, event
        k += 1


def events_manager(Players: list, event_number: int, bool: bool) -> None:
    """A function that will trigger and analyse all the events
    generated by the function generate_events, it also call the function
    stream_analytics to display some event state like the number of events that
    occured, the number of treasur event and the number of leveled up event

    Args:
        Players (list): all the players on the server
        event_number (int): how many events you want
        bool (bool): True if you want to see only
                     the first three line of events
    """
    total_event_count = 0
    treasur_event = 0
    level_up_event = 0

    print(f"Processing {event_number} game events...\n")
    for player, event in generate_events(Players, event_number):
        if (bool is False or total_event_count < 3):
            print(f"Event {total_event_count + 1}: Player {player['name']} \
({player['level']}) {event['event_name']}")
        if (bool is True and total_event_count == 3):
            print("...")
        total_event_count += 1
        if (event["event_name"] == "found treasure" or
                event["event_name"] == "found rare treasure"):
            treasur_event += 1
        if (event["event_name"] == "leveled up"):
            level_up_event += 1
    stream_analytics(Players, total_event_count, treasur_event, level_up_event)


def tool(Players: list):
    """tools for dev, let you see the players their stats

    Args:
        Players (list): All players on the server
    """
    for player in Players:
        print(f"tool == {player} ==")


if (__name__ == "__main__"):
    start = time.time()
    hide_lines = True

    print("=== Game Dat Stream Processor ===\n")
    events_manager(Players, 1000, hide_lines)

    print("\nMemory usage: Constant (streaming)")
    end = time.time()
    print(f"Processing time {round(end - start, 3)} second")

    # print("\n")
    # tool(Players)
    print("\n=== Generator Demonstration ===")
    fibonacci(10)
    prime_number(5)
